FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache curl libc6-compat openssl

COPY package*.json ./
COPY prisma ./prisma

RUN npm install
RUN npx prisma generate

COPY . .

EXPOSE 5000

ENV PORT=5000
ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
