FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache curl libc6-compat

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5000

ENV PORT=5000
ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
