-- Finalized Gritmode schema baseline.
-- Safe on the existing Supabase database: every object is guarded with IF NOT EXISTS.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN CREATE TYPE role_account AS ENUM ('customer','admin'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE status_account AS ENUM ('active','inactive','blocked'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE status_cart AS ENUM ('active','converted','abandoned'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE status_order AS ENUM ('pending','confirmed','processing','shipping','completed','cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE payment_method AS ENUM ('cod','payos'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE status_payment AS ENUM ('pending','processing','paid','expired','failed','cancelled','refunded'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE discount_type AS ENUM ('percentage','fixed_amount'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE status_product AS ENUM ('draft','active','archived'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE auth_provider AS ENUM ('local','google'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "user" (
  user_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email varchar(255) UNIQUE NOT NULL,
  status status_account NOT NULL DEFAULT 'active', role role_account NOT NULL DEFAULT 'customer',
  full_name varchar(255), url_image varchar(1000), date_of_birth date, gender boolean, phone varchar(20) UNIQUE,
  email_verified_at timestamp, created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS user_address (
  user_address_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL REFERENCES "user"(user_id),
  receiver_name_user_address varchar(255) NOT NULL, phone_user_address varchar(20) NOT NULL,
  address_line_user_address varchar(500) NOT NULL, ward_user_address varchar(150), district_user_address varchar(150),
  province_user_address varchar(150), is_default boolean NOT NULL DEFAULT false,
  created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS user_session (
  user_session_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL REFERENCES "user"(user_id),
  refresh_token_hash varchar(255) UNIQUE NOT NULL, user_agent varchar(500), ip_address varchar(100),
  expired_at timestamp NOT NULL, revoked_at timestamp, created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS email_otp (
  email_otp_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email varchar(255) NOT NULL,
  otp_hash varchar(255) NOT NULL, attempt_count int NOT NULL DEFAULT 0, expired_at timestamp NOT NULL,
  verified_at timestamp, created_at timestamp DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product (
  product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name_product varchar(255) NOT NULL,
  description text, status_product status_product NOT NULL DEFAULT 'draft', created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS category (
  category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, parent_category_id bigint REFERENCES category(category_id),
  name_category varchar(255) NOT NULL, slug_category varchar(255) UNIQUE NOT NULL, description_category text,
  position_category int NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true,
  created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS collection (
  collection_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name_collection varchar(255) NOT NULL,
  slug_collection varchar(255) UNIQUE NOT NULL, description_collection text, image_collection varchar(1000),
  is_active boolean NOT NULL DEFAULT true, start_at timestamp, end_at timestamp,
  created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS product_category (
  product_id bigint NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  category_id bigint NOT NULL REFERENCES category(category_id) ON DELETE CASCADE,
  is_primary boolean NOT NULL DEFAULT false, PRIMARY KEY (product_id, category_id)
);
CREATE TABLE IF NOT EXISTS product_collection (
  product_id bigint NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  collection_id bigint NOT NULL REFERENCES collection(collection_id) ON DELETE CASCADE,
  position_product_collection int NOT NULL DEFAULT 0, PRIMARY KEY (product_id, collection_id)
);
CREATE TABLE IF NOT EXISTS product_option (
  product_option_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  name_option varchar(100) NOT NULL, created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS product_option_value (
  product_option_value_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_option_id bigint NOT NULL REFERENCES product_option(product_option_id) ON DELETE CASCADE,
  value_option varchar(100) NOT NULL, created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS product_variant (
  product_variant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  sku varchar(100) UNIQUE NOT NULL, price bigint NOT NULL, created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS product_variant_option_value (
  product_variant_id bigint NOT NULL REFERENCES product_variant(product_variant_id) ON DELETE CASCADE,
  product_option_value_id bigint NOT NULL REFERENCES product_option_value(product_option_value_id) ON DELETE CASCADE,
  PRIMARY KEY (product_variant_id, product_option_value_id)
);
CREATE TABLE IF NOT EXISTS product_image (
  product_image_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  product_option_value_id bigint REFERENCES product_option_value(product_option_value_id) ON DELETE SET NULL,
  url_product_image varchar(1000) NOT NULL, alt_product_image varchar(255), position_product_image int NOT NULL DEFAULT 0,
  created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS inventory (
  inventory_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_variant_id bigint UNIQUE NOT NULL REFERENCES product_variant(product_variant_id) ON DELETE CASCADE,
  quantity_stock int NOT NULL DEFAULT 0, quantity_reserved int NOT NULL DEFAULT 0,
  created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cart (
  cart_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid REFERENCES "user"(user_id),
  guest_token varchar(255) UNIQUE, status_cart status_cart NOT NULL DEFAULT 'active',
  created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS cart_item (
  cart_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cart_id bigint NOT NULL REFERENCES cart(cart_id) ON DELETE CASCADE,
  product_variant_id bigint NOT NULL REFERENCES product_variant(product_variant_id), quantity_cart_item int NOT NULL DEFAULT 1,
  created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW(), UNIQUE (cart_id, product_variant_id)
);
CREATE TABLE IF NOT EXISTS voucher (
  voucher_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code_voucher varchar(100) UNIQUE NOT NULL,
  name_voucher varchar(255) NOT NULL, discount_type discount_type NOT NULL, discount_value bigint NOT NULL,
  minimum_order_amount bigint NOT NULL DEFAULT 0, maximum_discount_amount bigint, usage_limit int,
  usage_count int NOT NULL DEFAULT 0, start_at timestamp, end_at timestamp, is_active boolean NOT NULL DEFAULT true,
  created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS "order" (
  order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_code varchar(50) UNIQUE NOT NULL,
  user_id uuid REFERENCES "user"(user_id), cart_id bigint REFERENCES cart(cart_id), voucher_id bigint REFERENCES voucher(voucher_id),
  code_voucher_order varchar(100), email_order varchar(255) NOT NULL, phone_order varchar(20) NOT NULL,
  status_order status_order NOT NULL DEFAULT 'pending', subtotal_order bigint NOT NULL DEFAULT 0,
  discount_order bigint NOT NULL DEFAULT 0, shipping_fee_order bigint NOT NULL DEFAULT 0, total_order bigint NOT NULL DEFAULT 0,
  note_order text, created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS order_item (
  order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id bigint NOT NULL REFERENCES "order"(order_id) ON DELETE CASCADE,
  product_variant_id bigint REFERENCES product_variant(product_variant_id), name_product_order_item varchar(255) NOT NULL,
  sku_order_item varchar(100), variant_order_item varchar(255), price_order_item bigint NOT NULL,
  quantity_order_item int NOT NULL, total_order_item bigint NOT NULL, created_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS order_address (
  order_address_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id bigint UNIQUE NOT NULL REFERENCES "order"(order_id) ON DELETE CASCADE,
  receiver_name_order_address varchar(255) NOT NULL, phone_order_address varchar(20) NOT NULL,
  address_line_order_address varchar(500) NOT NULL, ward_order_address varchar(150), district_order_address varchar(150),
  province_order_address varchar(150), created_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS payment (
  payment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id bigint NOT NULL REFERENCES "order"(order_id) ON DELETE CASCADE,
  payment_method payment_method NOT NULL, status_payment status_payment NOT NULL DEFAULT 'pending', amount_payment bigint NOT NULL,
  payos_order_code bigint UNIQUE, payos_payment_link_id varchar(255) UNIQUE, payos_transaction_reference varchar(255),
  checkout_url varchar(1000), qr_code text, expired_at timestamp, paid_at timestamp,
  created_at timestamp DEFAULT NOW(), updated_at timestamp DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS admin_audit_log (
  admin_audit_log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid REFERENCES "user"(user_id),
  action_admin_audit_log varchar(100) NOT NULL, entity_admin_audit_log varchar(100) NOT NULL,
  entity_id_admin_audit_log varchar(100), old_data text, new_data text, created_at timestamp DEFAULT NOW()
);
