CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN CREATE TYPE auth_provider AS ENUM ('local','google'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE role_account AS ENUM ('customer','admin'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE status_account AS ENUM ('active','inactive','blocked'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE status_cart AS ENUM ('active','converted','abandoned'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "user" (
  user_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email varchar UNIQUE NOT NULL, password varchar,
  type auth_provider NOT NULL, status status_account NOT NULL DEFAULT 'active', role role_account NOT NULL DEFAULT 'customer',
  full_name varchar(255) NOT NULL, url_image varchar, date_of_birth date, gender boolean, phone varchar(20) UNIQUE
);
CREATE TABLE IF NOT EXISTS user_address (
  user_address_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL REFERENCES "user"(user_id),
  receiver_name_user_address varchar(255) NOT NULL, phone_user_address varchar(20) NOT NULL,
  address_line_user_address varchar(500) NOT NULL, ward_user_address varchar(150), district_user_address varchar(150),
  province_user_address varchar(150), is_default boolean NOT NULL DEFAULT false,
  created_at timestamp NOT NULL DEFAULT NOW(), updated_at timestamp NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS user_session (
  user_session_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL REFERENCES "user"(user_id),
  refresh_token_hash varchar(255) UNIQUE NOT NULL, user_agent varchar(500), ip_address varchar(100),
  expired_at timestamp NOT NULL, revoked_at timestamp, created_at timestamp NOT NULL DEFAULT NOW(), updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cart (
  cart_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES "user"(user_id), guest_token varchar(255),
  status_cart status_cart NOT NULL DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT NOW(), updated_at timestamp NOT NULL DEFAULT NOW()
);

ALTER TABLE cart ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE cart ADD COLUMN IF NOT EXISTS guest_token varchar(255);
CREATE UNIQUE INDEX IF NOT EXISTS uq_cart_guest_token ON cart(guest_token) WHERE guest_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_cart_user_status ON cart(user_id,status_cart);
CREATE INDEX IF NOT EXISTS idx_user_session_user ON user_session(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_default_address ON user_address(user_id) WHERE is_default=true;
DO $$ BEGIN
  ALTER TABLE cart ADD CONSTRAINT ck_cart_exactly_one_owner
    CHECK ((user_id IS NOT NULL AND guest_token IS NULL) OR (user_id IS NULL AND guest_token IS NOT NULL));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
