-- Migration 002: Product Catalog & Admin Audit Log

CREATE TABLE IF NOT EXISTS product (
  product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_product varchar(255) NOT NULL,
  description text,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS category (
  category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_category varchar(255) NOT NULL,
  parent_id bigint REFERENCES category(category_id) ON DELETE SET NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_category (
  product_id bigint NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  category_id bigint NOT NULL REFERENCES category(category_id) ON DELETE CASCADE,
  is_primary boolean NOT NULL DEFAULT false,
  PRIMARY KEY (product_id, category_id)
);

CREATE TABLE IF NOT EXISTS collection (
  collection_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_collection varchar(255) NOT NULL,
  description text,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_collection (
  product_id bigint NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  collection_id bigint NOT NULL REFERENCES collection(collection_id) ON DELETE CASCADE,
  PRIMARY KEY (product_id, collection_id)
);

CREATE TABLE IF NOT EXISTS product_option (
  product_option_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  name_option varchar(100) NOT NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_option_value (
  product_option_value_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_option_id bigint NOT NULL REFERENCES product_option(product_option_id) ON DELETE CASCADE,
  value_option varchar(100) NOT NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_image (
  product_image_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  product_option_value_id bigint REFERENCES product_option_value(product_option_value_id) ON DELETE SET NULL,
  url_product_image varchar(1000) NOT NULL,
  position_product_image int NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_variant (
  product_variant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES product(product_id) ON DELETE CASCADE,
  sku varchar(100) UNIQUE NOT NULL,
  price numeric(15, 2) NOT NULL,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS product_variant_option_value (
  product_variant_id bigint NOT NULL REFERENCES product_variant(product_variant_id) ON DELETE CASCADE,
  product_option_value_id bigint NOT NULL REFERENCES product_option_value(product_option_value_id) ON DELETE CASCADE,
  PRIMARY KEY (product_variant_id, product_option_value_id)
);

CREATE TABLE IF NOT EXISTS inventory (
  inventory_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_variant_id bigint UNIQUE NOT NULL REFERENCES product_variant(product_variant_id) ON DELETE CASCADE,
  quantity_stock int NOT NULL DEFAULT 0,
  quantity_reserved int NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin_audit_log (
  audit_log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES "user"(user_id) ON DELETE SET NULL,
  action varchar(100) NOT NULL,
  entity_name varchar(100) NOT NULL,
  entity_id varchar(100) NOT NULL,
  old_data jsonb,
  new_data jsonb,
  created_at timestamp NOT NULL DEFAULT NOW()
);

-- Indexes for optimal search, filtering and sorting
CREATE INDEX IF NOT EXISTS idx_product_name ON product(name_product);
CREATE INDEX IF NOT EXISTS idx_product_created_at ON product(created_at);
CREATE INDEX IF NOT EXISTS idx_product_variant_price ON product_variant(price);
CREATE INDEX IF NOT EXISTS idx_product_variant_product_id ON product_variant(product_id);
CREATE INDEX IF NOT EXISTS idx_product_category_cat_id ON product_category(category_id);
CREATE INDEX IF NOT EXISTS idx_product_collection_col_id ON product_collection(collection_id);
CREATE INDEX IF NOT EXISTS idx_product_image_product_pos ON product_image(product_id, position_product_image);
