-- Replace password/provider authentication persistence with email OTP persistence.
-- This migration intentionally follows the finalized DBML schema.

ALTER TABLE "user"
  ADD COLUMN IF NOT EXISTS email_verified_at timestamp,
  ADD COLUMN IF NOT EXISTS created_at timestamp,
  ADD COLUMN IF NOT EXISTS updated_at timestamp;

UPDATE "user"
SET status = COALESCE(status, 'active'),
    role = COALESCE(role, 'customer'),
    created_at = COALESCE(created_at, NOW()),
    updated_at = COALESCE(updated_at, NOW());

ALTER TABLE "user"
  ALTER COLUMN email TYPE varchar(255),
  ALTER COLUMN email SET NOT NULL,
  ALTER COLUMN status SET DEFAULT 'active',
  ALTER COLUMN status SET NOT NULL,
  ALTER COLUMN role SET DEFAULT 'customer',
  ALTER COLUMN role SET NOT NULL,
  ALTER COLUMN full_name DROP NOT NULL,
  ALTER COLUMN url_image TYPE varchar(1000);

CREATE TABLE IF NOT EXISTS email_otp (
  email_otp_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL,
  otp_hash varchar(255) NOT NULL,
  attempt_count int NOT NULL DEFAULT 0,
  expired_at timestamp NOT NULL,
  verified_at timestamp,
  created_at timestamp
);

CREATE INDEX IF NOT EXISTS idx_email_otp_email
  ON email_otp(email);

CREATE INDEX IF NOT EXISTS idx_email_otp_email_created_at
  ON email_otp(email, created_at);

ALTER TABLE "user"
  DROP COLUMN IF EXISTS password,
  DROP COLUMN IF EXISTS type;

DO $$ BEGIN
  DROP TYPE IF EXISTS auth_provider;
EXCEPTION
  WHEN dependent_objects_still_exist THEN NULL;
END $$;
