DO $$ BEGIN CREATE TYPE status_order AS ENUM ('pending','confirmed','processing','shipping','completed','cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE payment_method AS ENUM ('cod','payos'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE status_payment AS ENUM ('pending','paid','failed','refunded','cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS "order" (
  order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_code varchar(50) NOT NULL UNIQUE,
  user_id uuid REFERENCES "user"(user_id),
  cart_id bigint REFERENCES cart(cart_id),
  voucher_id bigint REFERENCES voucher(voucher_id),
  code_voucher_order varchar(100),
  email_order varchar(255) NOT NULL,
  phone_order varchar(20) NOT NULL,
  status_order status_order NOT NULL DEFAULT 'pending',
  subtotal_order bigint NOT NULL DEFAULT 0,
  discount_order bigint NOT NULL DEFAULT 0,
  shipping_fee_order bigint NOT NULL DEFAULT 0,
  total_order bigint NOT NULL DEFAULT 0,
  note_order text,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_item (
  order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES "order"(order_id) ON DELETE CASCADE,
  product_variant_id bigint REFERENCES product_variant(product_variant_id),
  name_product_order_item varchar(255) NOT NULL,
  sku_order_item varchar(100),
  variant_order_item varchar(255),
  price_order_item bigint NOT NULL,
  quantity_order_item int NOT NULL,
  total_order_item bigint NOT NULL,
  created_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_address (
  order_address_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL UNIQUE REFERENCES "order"(order_id) ON DELETE CASCADE,
  receiver_name_order_address varchar(255) NOT NULL,
  phone_order_address varchar(20) NOT NULL,
  address_line_order_address varchar(500) NOT NULL,
  ward_order_address varchar(150),
  district_order_address varchar(150),
  province_order_address varchar(150),
  created_at timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment (
  payment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES "order"(order_id) ON DELETE CASCADE,
  payment_method payment_method NOT NULL,
  status_payment status_payment NOT NULL DEFAULT 'pending',
  amount_payment bigint NOT NULL,
  payos_order_code bigint UNIQUE,
  payos_payment_link_id varchar(255),
  checkout_url text,
  qr_code text,
  expired_at timestamp,
  paid_at timestamp,
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_order_user_id ON "order"(user_id);
CREATE INDEX IF NOT EXISTS idx_order_status ON "order"(status_order);
CREATE INDEX IF NOT EXISTS idx_order_created_at ON "order"(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_item_order_id ON order_item(order_id);
CREATE INDEX IF NOT EXISTS idx_payment_order_id ON payment(order_id);
