CREATE TABLE IF NOT EXISTS notification_outbox (
  notification_outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel VARCHAR(32) NOT NULL DEFAULT 'email',
  event_type VARCHAR(80) NOT NULL,
  destination VARCHAR(320) NOT NULL,
  dedupe_key VARCHAR(255) NOT NULL UNIQUE,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  attempt_count INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  locked_at TIMESTAMPTZ,
  last_error TEXT,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT notification_outbox_status_check
    CHECK (status IN ('pending', 'processing', 'sent', 'failed', 'dead_letter'))
);

CREATE INDEX IF NOT EXISTS idx_notification_outbox_claim
  ON notification_outbox (status, next_attempt_at, notification_outbox_id);

CREATE TABLE IF NOT EXISTS admin_notification (
  admin_notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(80) NOT NULL,
  entity_type VARCHAR(80),
  entity_id BIGINT,
  dedupe_key VARCHAR(255) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_admin_notification_created_at
  ON admin_notification (created_at DESC, admin_notification_id DESC);

CREATE TABLE IF NOT EXISTS admin_notification_read (
  admin_notification_id BIGINT NOT NULL REFERENCES admin_notification(admin_notification_id) ON DELETE CASCADE,
  admin_user_id UUID NOT NULL REFERENCES "user"(user_id) ON DELETE CASCADE,
  read_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (admin_notification_id, admin_user_id)
);

CREATE INDEX IF NOT EXISTS idx_admin_notification_read_user
  ON admin_notification_read (admin_user_id, read_at DESC);
